name: Feature request
description: Describe a concrete use case for a component or tool.
title: "[Feature] "
body:
  - type: textarea
    id: usecase
    attributes:
      label: What problem are you trying to solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior and example
    validations:
      required: true
